[package]
name = "gclf-hyaline"
version = "0.1.0"
authors = ["abishek"]
edition = "2018"

[dependencies]
atomicdouble = "0.1.3"

[dependencies.educe]
version = "0.4.18"
features = ["Debug"]
default-features = false